# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do evento: ')),
                ('time', models.CharField(max_length=4, verbose_name='Tempo do evento')),
                ('init_hour', models.CharField(max_length=4, verbose_name='Hora de inicio')),
                ('finish_hour', models.CharField(max_length=4, verbose_name='Hora de t\xe9rmino')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Logo do evento')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
            ],
        ),
    ]
