# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 18:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Texto'),
        ),
    ]
