# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 18:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20160329_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='finish_hour',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='init_hour',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='text',
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default=b'Evento Teste ', max_length=255, verbose_name='Nome do evento'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='text_1',
            field=ckeditor.fields.RichTextField(default=b'Conferimos o presente certificado a', max_length=255, verbose_name='Texto 1'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='text_2',
            field=ckeditor.fields.RichTextField(default=b'realizada(o) no(s) dia(s)', max_length=255, verbose_name='Texto 2'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='text_3',
            field=ckeditor.fields.RichTextField(default=b'com dura\xc3\xa7\xc3\xa3o total de ', max_length=255, verbose_name='Texto 3'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.CharField(default=b'10 e 11 de janeiro de 2016', max_length=255, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='time',
            field=models.CharField(default=b'10 horas', max_length=4, verbose_name='Tempo do evento'),
        ),
    ]
