# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_auto_20160329_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='time',
            field=models.CharField(default=b'10 horas', max_length=255, verbose_name='Tempo do evento'),
        ),
    ]
